#!/usr/bin/env python3
"""Harvest the files a review cell wrote into its clone, without running git.

Replaces the `git -C "$clone" status --porcelain -z --untracked-files=all` the
runner used to pipe into a bash loop. Two reasons, in order of importance:

1. **It was host git against a container-written `.git`.** That `git status` was
   the FIRST host command after the review container exited, which is precisely
   where `core.fsmonitor` fires — one of five host-side code-execution paths the
   2026-08-19 review executed (rubric R1). Nothing in this file reads `.git`.
2. **It was incomplete.** `--untracked-files=all` still honours `.gitignore`, so
   a rubric written to a path the upstream repo ignores was invisible, and the
   code-review skill writes its rubric under `docs/reviews/`. Measured on the
   five materialized pilot clones: none ignores `docs/reviews/` specifically and
   two ignore other `docs/`-adjacent paths — so this is a guard against a real
   mechanism rather than an observed loss, and the earlier wording ("several
   benchmark repos ignore `docs/`-adjacent paths") overstated the corpus.

The comparison is against the baseline index written by
`crb-materialize.py --snapshot` ({relpath: sha256} over the clone's .md/.json
files, .git excluded), so "wrote" means new-or-changed relative to the pristine
tree the cell started from — which, with disposable clones, is exactly the tree
it was given.

Everything here treats the clone as untrusted content from a third-party repo:
paths are generated by walking rather than parsed, symlinks are never followed
or copied, and per-file and total size caps stop a hostile or runaway repo from
filling the host disk with "artifacts".

Usage:
  crb-harvest-artifacts.py <clone> <baseline-index.json> <dest-artifacts-dir>
Exit: 0 harvested (possibly nothing) · 2 usage/invocation error.
"""

import hashlib
import json
import os
import shutil
import sys
from pathlib import Path

SUFFIXES = (".md", ".json")
# A rubric is a few KB and a critic report tens of KB. The caps exist so a
# pathological repo cannot turn the harvest into a disk-fill; they are far above
# anything the pipeline legitimately writes, and both are reported when hit
# rather than silently truncating the record.
MAX_FILE_BYTES = 5 * 1024 * 1024
MAX_TOTAL_BYTES = 50 * 1024 * 1024
MAX_FILES = 500


def sha256_file(path: Path, _bufsize: int = 1 << 20) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as fh:
        for chunk in iter(lambda: fh.read(_bufsize), b""):
            h.update(chunk)
    return h.hexdigest()


def changed_artifacts(clone: Path, baseline: dict):
    """[(relpath, reason)] for .md/.json files new or changed since the baseline."""
    found = []
    for root, dirs, files in os.walk(clone, followlinks=False):
        # Same exclusions as artifact_index() in crb-materialize.py, and they
        # must stay the same: a directory skipped there but walked here reports
        # every file inside it as "new" on the first cell.
        dirs[:] = [d for d in dirs
                   if d != ".git" and not (Path(root) / d).is_symlink()]
        for name in files:
            if not name.endswith(SUFFIXES):
                continue
            fp = Path(root) / name
            # A symlink is not an artifact, and copying one preserves a pointer
            # into the host filesystem that a later reader would follow.
            if fp.is_symlink() or not fp.is_file():
                continue
            rel = str(fp.relative_to(clone))
            prior = baseline.get(rel)
            if prior is None:
                found.append((rel, "new"))
            elif sha256_file(fp) != prior:
                found.append((rel, "modified"))
    return sorted(found)


def main(argv):
    if len(argv) != 4:
        # Exit 2, never 1: the caller distinguishes "nothing to harvest" from
        # "this invocation is broken", and conflating them is how a bug becomes
        # a silently empty artifacts dir on a $10-40 cell.
        print("usage: crb-harvest-artifacts.py <clone> <baseline-index.json> "
              "<dest-artifacts-dir>", file=sys.stderr)
        return 2
    clone, index_path, dest = Path(argv[1]), Path(argv[2]), Path(argv[3])
    if not clone.is_dir():
        print(f"no clone at {clone}", file=sys.stderr)
        return 2
    if not index_path.is_file():
        # Failing rather than treating "no baseline" as "everything is new":
        # that would copy every .md/.json in a 195 MB upstream repo into the
        # cell dir and report it as pipeline output.
        print(f"no baseline index at {index_path} — run "
              f"`crb-materialize.py --snapshot` for this slug", file=sys.stderr)
        return 2
    baseline = json.loads(index_path.read_text())
    dest.mkdir(parents=True, exist_ok=True)

    total = 0
    copied = skipped = 0
    for rel, reason in changed_artifacts(clone, baseline):
        src = clone / rel
        size = src.stat().st_size
        if size > MAX_FILE_BYTES:
            print(f"  !! skipping {rel}: {size} bytes exceeds the "
                  f"{MAX_FILE_BYTES}-byte per-file cap", file=sys.stderr)
            skipped += 1
            continue
        if copied >= MAX_FILES or total + size > MAX_TOTAL_BYTES:
            print(f"  !! harvest cap reached ({copied} files, {total} bytes) — "
                  f"remaining artifacts NOT captured", file=sys.stderr)
            skipped += 1
            break
        out = dest / rel
        out.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(src, out)   # copyfile, not copy2: no mode bits carried over
        total += size
        copied += 1
        print(f"  artifact ({reason}): {rel}")
    print(f"  harvested {copied} artifact(s), {total} bytes"
          + (f", {skipped} skipped" if skipped else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
